// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEscovmORK-Rg1oNTeXnOmr41h-pbsrLs',
    appId: '1:485969412653:web:e0cb381f153f8276672ea4',
    messagingSenderId: '485969412653',
    projectId: 'work-space-f67ef',
    authDomain: 'work-space-f67ef.firebaseapp.com',
    storageBucket: 'work-space-f67ef.firebasestorage.app',
    measurementId: 'G-FVEHZE10N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjugD-XiuHaKjiKh3E4iraxOE6EqcLln0',
    appId: '1:485969412653:android:ac9a18e94c0eb2ad672ea4',
    messagingSenderId: '485969412653',
    projectId: 'work-space-f67ef',
    storageBucket: 'work-space-f67ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSYwMAI23-SRVRwQUPewE4mWg3EWLzIdg',
    appId: '1:485969412653:ios:f1c222d643a4cfc9672ea4',
    messagingSenderId: '485969412653',
    projectId: 'work-space-f67ef',
    storageBucket: 'work-space-f67ef.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSYwMAI23-SRVRwQUPewE4mWg3EWLzIdg',
    appId: '1:485969412653:ios:f1c222d643a4cfc9672ea4',
    messagingSenderId: '485969412653',
    projectId: 'work-space-f67ef',
    storageBucket: 'work-space-f67ef.firebasestorage.app',
    iosBundleId: 'com.example.workspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEscovmORK-Rg1oNTeXnOmr41h-pbsrLs',
    appId: '1:485969412653:web:bb57efa70ffb3346672ea4',
    messagingSenderId: '485969412653',
    projectId: 'work-space-f67ef',
    authDomain: 'work-space-f67ef.firebaseapp.com',
    storageBucket: 'work-space-f67ef.firebasestorage.app',
    measurementId: 'G-KS9FC2XHYJ',
  );
}
